using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Terminology.Permissions;
using Terminology.Terms;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Terminology.Shared;

namespace Terminology.Terms
{
    public class TermsAppService : TermsAppServiceBase, ITermsAppService
    {
        //<suite-custom-code-autogenerated>
        public TermsAppService(ITermRepository termRepository, TermManager termManager, IDistributedCache<TermDownloadTokenCacheItem, string> downloadTokenCache)
            : base(termRepository, termManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}