using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Terminology.Terms
{
    public class TermManager : TermManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TermManager(ITermRepository termRepository)
            : base(termRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}